<?xml version="1.0" encoding="utf-8"?><Database Name="pet_store" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\pet_store.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="pet_storeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.pets" Member="pets">
    <Type Name="pet">
      <Column Name="pet_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="owner_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="owner_pet" Member="owner" ThisKey="owner_id" OtherKey="owner_id" Type="owner" IsForeignKey="true" />
      <Association Name="pet_type_pet" Member="pet_type" ThisKey="type_id" OtherKey="type_id" Type="pet_type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.owners" Member="owners">
    <Type Name="owner">
      <Column Name="owner_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="lname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="owner_pet" Member="pets" ThisKey="owner_id" OtherKey="owner_id" Type="pet" />
    </Type>
  </Table>
  <Table Name="dbo.pet_type" Member="pet_types">
    <Type Name="pet_type">
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="pet_type_pet" Member="pets" ThisKey="type_id" OtherKey="type_id" Type="pet" />
    </Type>
  </Table>
  <Table Name="dbo.store" Member="stores">
    <Type Name="store">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ime_ljubimca" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="godine" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="opis" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="ime_vlasnika" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="prezime_vlasnika" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="adresa" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="tip" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.cats" Member="cats">
    <Type Name="cat">
      <Column Name="pet_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="owner_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.dogs" Member="dogs">
    <Type Name="dog">
      <Column Name="pet_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="owner_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.hamsters" Member="hamsters">
    <Type Name="hamster">
      <Column Name="pet_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="owner_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>