#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilicaZivkovic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mobilnaTelefonija")]
	public partial class TelefonijaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkartica(kartica instance);
    partial void Updatekartica(kartica instance);
    partial void Deletekartica(kartica instance);
    partial void Insertkorisnik(korisnik instance);
    partial void Updatekorisnik(korisnik instance);
    partial void Deletekorisnik(korisnik instance);
    partial void Insertsaobracaj(saobracaj instance);
    partial void Updatesaobracaj(saobracaj instance);
    partial void Deletesaobracaj(saobracaj instance);
    partial void Inserttelefon(telefon instance);
    partial void Updatetelefon(telefon instance);
    partial void Deletetelefon(telefon instance);
    partial void InserttipSaobracaja(tipSaobracaja instance);
    partial void UpdatetipSaobracaja(tipSaobracaja instance);
    partial void DeletetipSaobracaja(tipSaobracaja instance);
    #endregion
		
		public TelefonijaDataContext() : 
				base(global::MilicaZivkovic.Properties.Settings.Default.mobilnaTelefonijaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonijaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonijaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonijaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TelefonijaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<kartica> karticas
		{
			get
			{
				return this.GetTable<kartica>();
			}
		}
		
		public System.Data.Linq.Table<korisnik> korisniks
		{
			get
			{
				return this.GetTable<korisnik>();
			}
		}
		
		public System.Data.Linq.Table<saobracaj> saobracajs
		{
			get
			{
				return this.GetTable<saobracaj>();
			}
		}
		
		public System.Data.Linq.Table<telefon> telefons
		{
			get
			{
				return this.GetTable<telefon>();
			}
		}
		
		public System.Data.Linq.Table<tipSaobracaja> tipSaobracajas
		{
			get
			{
				return this.GetTable<tipSaobracaja>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kartica")]
	public partial class kartica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _broj;
		
		private string _operater;
		
		private EntitySet<saobracaj> _saobracajs;
		
		private EntitySet<telefon> _telefons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbrojChanging(string value);
    partial void OnbrojChanged();
    partial void OnoperaterChanging(string value);
    partial void OnoperaterChanged();
    #endregion
		
		public kartica()
		{
			this._saobracajs = new EntitySet<saobracaj>(new Action<saobracaj>(this.attach_saobracajs), new Action<saobracaj>(this.detach_saobracajs));
			this._telefons = new EntitySet<telefon>(new Action<telefon>(this.attach_telefons), new Action<telefon>(this.detach_telefons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_broj", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string broj
		{
			get
			{
				return this._broj;
			}
			set
			{
				if ((this._broj != value))
				{
					this.OnbrojChanging(value);
					this.SendPropertyChanging();
					this._broj = value;
					this.SendPropertyChanged("broj");
					this.OnbrojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operater", DbType="VarChar(20)")]
		public string operater
		{
			get
			{
				return this._operater;
			}
			set
			{
				if ((this._operater != value))
				{
					this.OnoperaterChanging(value);
					this.SendPropertyChanging();
					this._operater = value;
					this.SendPropertyChanged("operater");
					this.OnoperaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kartica_saobracaj", Storage="_saobracajs", ThisKey="id", OtherKey="idKartice")]
		public EntitySet<saobracaj> saobracajs
		{
			get
			{
				return this._saobracajs;
			}
			set
			{
				this._saobracajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kartica_telefon", Storage="_telefons", ThisKey="id", OtherKey="idkartice")]
		public EntitySet<telefon> telefons
		{
			get
			{
				return this._telefons;
			}
			set
			{
				this._telefons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saobracajs(saobracaj entity)
		{
			this.SendPropertyChanging();
			entity.kartica = this;
		}
		
		private void detach_saobracajs(saobracaj entity)
		{
			this.SendPropertyChanging();
			entity.kartica = null;
		}
		
		private void attach_telefons(telefon entity)
		{
			this.SendPropertyChanging();
			entity.kartica = this;
		}
		
		private void detach_telefons(telefon entity)
		{
			this.SendPropertyChanging();
			entity.kartica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.korisnik")]
	public partial class korisnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ime;
		
		private System.Nullable<System.DateTime> _datumRodjenja;
		
		private string _adresa;
		
		private EntitySet<telefon> _telefons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnimeChanging(string value);
    partial void OnimeChanged();
    partial void OndatumRodjenjaChanging(System.Nullable<System.DateTime> value);
    partial void OndatumRodjenjaChanged();
    partial void OnadresaChanging(string value);
    partial void OnadresaChanged();
    #endregion
		
		public korisnik()
		{
			this._telefons = new EntitySet<telefon>(new Action<telefon>(this.attach_telefons), new Action<telefon>(this.detach_telefons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				if ((this._ime != value))
				{
					this.OnimeChanging(value);
					this.SendPropertyChanging();
					this._ime = value;
					this.SendPropertyChanged("ime");
					this.OnimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datumRodjenja", DbType="DateTime")]
		public System.Nullable<System.DateTime> datumRodjenja
		{
			get
			{
				return this._datumRodjenja;
			}
			set
			{
				if ((this._datumRodjenja != value))
				{
					this.OndatumRodjenjaChanging(value);
					this.SendPropertyChanging();
					this._datumRodjenja = value;
					this.SendPropertyChanged("datumRodjenja");
					this.OndatumRodjenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string adresa
		{
			get
			{
				return this._adresa;
			}
			set
			{
				if ((this._adresa != value))
				{
					this.OnadresaChanging(value);
					this.SendPropertyChanging();
					this._adresa = value;
					this.SendPropertyChanged("adresa");
					this.OnadresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="korisnik_telefon", Storage="_telefons", ThisKey="id", OtherKey="idKorisnika")]
		public EntitySet<telefon> telefons
		{
			get
			{
				return this._telefons;
			}
			set
			{
				this._telefons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_telefons(telefon entity)
		{
			this.SendPropertyChanging();
			entity.korisnik = this;
		}
		
		private void detach_telefons(telefon entity)
		{
			this.SendPropertyChanging();
			entity.korisnik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.saobracaj")]
	public partial class saobracaj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idKartice;
		
		private int _ostvareniSaobracaj;
		
		private int _idTipaSaobracaja;
		
		private System.Nullable<System.DateTime> _datum;
		
		private EntityRef<kartica> _kartica;
		
		private EntityRef<tipSaobracaja> _tipSaobracaja;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidKarticeChanging(int value);
    partial void OnidKarticeChanged();
    partial void OnostvareniSaobracajChanging(int value);
    partial void OnostvareniSaobracajChanged();
    partial void OnidTipaSaobracajaChanging(int value);
    partial void OnidTipaSaobracajaChanged();
    partial void OndatumChanging(System.Nullable<System.DateTime> value);
    partial void OndatumChanged();
    #endregion
		
		public saobracaj()
		{
			this._kartica = default(EntityRef<kartica>);
			this._tipSaobracaja = default(EntityRef<tipSaobracaja>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKartice", DbType="Int NOT NULL")]
		public int idKartice
		{
			get
			{
				return this._idKartice;
			}
			set
			{
				if ((this._idKartice != value))
				{
					if (this._kartica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKarticeChanging(value);
					this.SendPropertyChanging();
					this._idKartice = value;
					this.SendPropertyChanged("idKartice");
					this.OnidKarticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ostvareniSaobracaj", DbType="Int NOT NULL")]
		public int ostvareniSaobracaj
		{
			get
			{
				return this._ostvareniSaobracaj;
			}
			set
			{
				if ((this._ostvareniSaobracaj != value))
				{
					this.OnostvareniSaobracajChanging(value);
					this.SendPropertyChanging();
					this._ostvareniSaobracaj = value;
					this.SendPropertyChanged("ostvareniSaobracaj");
					this.OnostvareniSaobracajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipaSaobracaja", DbType="Int NOT NULL")]
		public int idTipaSaobracaja
		{
			get
			{
				return this._idTipaSaobracaja;
			}
			set
			{
				if ((this._idTipaSaobracaja != value))
				{
					if (this._tipSaobracaja.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipaSaobracajaChanging(value);
					this.SendPropertyChanging();
					this._idTipaSaobracaja = value;
					this.SendPropertyChanged("idTipaSaobracaja");
					this.OnidTipaSaobracajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum", DbType="DateTime")]
		public System.Nullable<System.DateTime> datum
		{
			get
			{
				return this._datum;
			}
			set
			{
				if ((this._datum != value))
				{
					this.OndatumChanging(value);
					this.SendPropertyChanging();
					this._datum = value;
					this.SendPropertyChanged("datum");
					this.OndatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kartica_saobracaj", Storage="_kartica", ThisKey="idKartice", OtherKey="id", IsForeignKey=true)]
		public kartica kartica
		{
			get
			{
				return this._kartica.Entity;
			}
			set
			{
				kartica previousValue = this._kartica.Entity;
				if (((previousValue != value) 
							|| (this._kartica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kartica.Entity = null;
						previousValue.saobracajs.Remove(this);
					}
					this._kartica.Entity = value;
					if ((value != null))
					{
						value.saobracajs.Add(this);
						this._idKartice = value.id;
					}
					else
					{
						this._idKartice = default(int);
					}
					this.SendPropertyChanged("kartica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipSaobracaja_saobracaj", Storage="_tipSaobracaja", ThisKey="idTipaSaobracaja", OtherKey="id", IsForeignKey=true)]
		public tipSaobracaja tipSaobracaja
		{
			get
			{
				return this._tipSaobracaja.Entity;
			}
			set
			{
				tipSaobracaja previousValue = this._tipSaobracaja.Entity;
				if (((previousValue != value) 
							|| (this._tipSaobracaja.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipSaobracaja.Entity = null;
						previousValue.saobracajs.Remove(this);
					}
					this._tipSaobracaja.Entity = value;
					if ((value != null))
					{
						value.saobracajs.Add(this);
						this._idTipaSaobracaja = value.id;
					}
					else
					{
						this._idTipaSaobracaja = default(int);
					}
					this.SendPropertyChanged("tipSaobracaja");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.telefon")]
	public partial class telefon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _marka;
		
		private int _idKorisnika;
		
		private int _idkartice;
		
		private EntityRef<kartica> _kartica;
		
		private EntityRef<korisnik> _korisnik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmarkaChanging(string value);
    partial void OnmarkaChanged();
    partial void OnidKorisnikaChanging(int value);
    partial void OnidKorisnikaChanged();
    partial void OnidkarticeChanging(int value);
    partial void OnidkarticeChanged();
    #endregion
		
		public telefon()
		{
			this._kartica = default(EntityRef<kartica>);
			this._korisnik = default(EntityRef<korisnik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marka", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string marka
		{
			get
			{
				return this._marka;
			}
			set
			{
				if ((this._marka != value))
				{
					this.OnmarkaChanging(value);
					this.SendPropertyChanging();
					this._marka = value;
					this.SendPropertyChanged("marka");
					this.OnmarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKorisnika", DbType="Int NOT NULL")]
		public int idKorisnika
		{
			get
			{
				return this._idKorisnika;
			}
			set
			{
				if ((this._idKorisnika != value))
				{
					if (this._korisnik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._idKorisnika = value;
					this.SendPropertyChanged("idKorisnika");
					this.OnidKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkartice", DbType="Int NOT NULL")]
		public int idkartice
		{
			get
			{
				return this._idkartice;
			}
			set
			{
				if ((this._idkartice != value))
				{
					if (this._kartica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidkarticeChanging(value);
					this.SendPropertyChanging();
					this._idkartice = value;
					this.SendPropertyChanged("idkartice");
					this.OnidkarticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kartica_telefon", Storage="_kartica", ThisKey="idkartice", OtherKey="id", IsForeignKey=true)]
		public kartica kartica
		{
			get
			{
				return this._kartica.Entity;
			}
			set
			{
				kartica previousValue = this._kartica.Entity;
				if (((previousValue != value) 
							|| (this._kartica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kartica.Entity = null;
						previousValue.telefons.Remove(this);
					}
					this._kartica.Entity = value;
					if ((value != null))
					{
						value.telefons.Add(this);
						this._idkartice = value.id;
					}
					else
					{
						this._idkartice = default(int);
					}
					this.SendPropertyChanged("kartica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="korisnik_telefon", Storage="_korisnik", ThisKey="idKorisnika", OtherKey="id", IsForeignKey=true)]
		public korisnik korisnik
		{
			get
			{
				return this._korisnik.Entity;
			}
			set
			{
				korisnik previousValue = this._korisnik.Entity;
				if (((previousValue != value) 
							|| (this._korisnik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._korisnik.Entity = null;
						previousValue.telefons.Remove(this);
					}
					this._korisnik.Entity = value;
					if ((value != null))
					{
						value.telefons.Add(this);
						this._idKorisnika = value.id;
					}
					else
					{
						this._idKorisnika = default(int);
					}
					this.SendPropertyChanged("korisnik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipSaobracaja")]
	public partial class tipSaobracaja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _naziv;
		
		private double _cenaPoOstvarenomSaobracaju;
		
		private EntitySet<saobracaj> _saobracajs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnazivChanging(string value);
    partial void OnnazivChanged();
    partial void OncenaPoOstvarenomSaobracajuChanging(double value);
    partial void OncenaPoOstvarenomSaobracajuChanged();
    #endregion
		
		public tipSaobracaja()
		{
			this._saobracajs = new EntitySet<saobracaj>(new Action<saobracaj>(this.attach_saobracajs), new Action<saobracaj>(this.detach_saobracajs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naziv", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string naziv
		{
			get
			{
				return this._naziv;
			}
			set
			{
				if ((this._naziv != value))
				{
					this.OnnazivChanging(value);
					this.SendPropertyChanging();
					this._naziv = value;
					this.SendPropertyChanged("naziv");
					this.OnnazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cenaPoOstvarenomSaobracaju", DbType="Float NOT NULL")]
		public double cenaPoOstvarenomSaobracaju
		{
			get
			{
				return this._cenaPoOstvarenomSaobracaju;
			}
			set
			{
				if ((this._cenaPoOstvarenomSaobracaju != value))
				{
					this.OncenaPoOstvarenomSaobracajuChanging(value);
					this.SendPropertyChanging();
					this._cenaPoOstvarenomSaobracaju = value;
					this.SendPropertyChanged("cenaPoOstvarenomSaobracaju");
					this.OncenaPoOstvarenomSaobracajuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipSaobracaja_saobracaj", Storage="_saobracajs", ThisKey="id", OtherKey="idTipaSaobracaja")]
		public EntitySet<saobracaj> saobracajs
		{
			get
			{
				return this._saobracajs;
			}
			set
			{
				this._saobracajs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saobracajs(saobracaj entity)
		{
			this.SendPropertyChanging();
			entity.tipSaobracaja = this;
		}
		
		private void detach_saobracajs(saobracaj entity)
		{
			this.SendPropertyChanging();
			entity.tipSaobracaja = null;
		}
	}
}
#pragma warning restore 1591
