<?xml version="1.0" encoding="utf-8"?><Database Name="mobilnaTelefonija" Class="TelefonijaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\telefonija;Initial Catalog=mobilnaTelefonija;Integrated Security=True" SettingsObjectName="MilicaZivkovic.Properties.Settings" SettingsPropertyName="mobilnaTelefonijaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.kartica" Member="karticas">
    <Type Name="kartica">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="broj" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="operater" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="kartica_saobracaj" Member="saobracajs" ThisKey="id" OtherKey="idKartice" Type="saobracaj" />
      <Association Name="kartica_telefon" Member="telefons" ThisKey="id" OtherKey="idkartice" Type="telefon" />
    </Type>
  </Table>
  <Table Name="dbo.korisnik" Member="korisniks">
    <Type Name="korisnik">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="datumRodjenja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="adresa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="korisnik_telefon" Member="telefons" ThisKey="id" OtherKey="idKorisnika" Type="telefon" />
    </Type>
  </Table>
  <Table Name="dbo.saobracaj" Member="saobracajs">
    <Type Name="saobracaj">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idKartice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ostvareniSaobracaj" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTipaSaobracaja" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="kartica_saobracaj" Member="kartica" ThisKey="idKartice" OtherKey="id" Type="kartica" IsForeignKey="true" />
      <Association Name="tipSaobracaja_saobracaj" Member="tipSaobracaja" ThisKey="idTipaSaobracaja" OtherKey="id" Type="tipSaobracaja" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.telefon" Member="telefons">
    <Type Name="telefon">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="marka" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idKorisnika" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idkartice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="kartica_telefon" Member="kartica" ThisKey="idkartice" OtherKey="id" Type="kartica" IsForeignKey="true" />
      <Association Name="korisnik_telefon" Member="korisnik" ThisKey="idKorisnika" OtherKey="id" Type="korisnik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tipSaobracaja" Member="tipSaobracajas">
    <Type Name="tipSaobracaja">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naziv" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="cenaPoOstvarenomSaobracaju" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="tipSaobracaja_saobracaj" Member="saobracajs" ThisKey="id" OtherKey="idTipaSaobracaja" Type="saobracaj" />
    </Type>
  </Table>
</Database>